language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: qrCKNIg1ysSItajWClKkUX1Y0593OfOaYAah2Ntx4+Rpk1sPRBW55mQwm9JimYF8kGeoiinQRXjk9xaQyGtKQPv4QrICQTDvIUNdMrsg9BF86PHOkUNOeQ/7jDA7w+oddnuCOieWlUTyDA3zNLt2ggPIKG53zULc0a86k/YgIhiNcH2+uZ0s9pN5kJtB0iJzSDdovATsdubgcNlJvHCAhxNY/cpNrHAhiM/Jphb5nkBs3FqK0WLg1dU7zTaK23hwzvGulCR2kYATsqYxXnpGv2br35xRXl8kDttY4zcRNktk4iM1s1pn/pLLho6xgEgVSnfD2vO88JM1nefG2A8RygT26OUO9mkwUSlViQ14V1hvKw1c/IKw3O7416E8oTjpwkDfI0tkuNXyODz0v476RORx6BE59y9hhHuM6H1Uy1eGmnI83nYLvpoJq+Qj0OlPAJ0erQIXy+pq/BErnGwznWnynwnM0tfehW4fvyRxLd7eVweNkOnH9avECWWwrkcu+zftMVlwNx3D/Q+Tq0pXWCgsCKp6iBDt/BCxFiJiqaKrRAFLjCegFCShM3+YFDPYMmel3zlJRl91BDazjEmN+wphVN35XLQZg36e51hiomLOoD1t+NPS0GJ1zXVxzszgJj7ntUxju6LIFk+lTFSK5oXj79D3sGihbmxuRHyASq0=
  - secure: G+e6Vj59gykzf9rB+5HdpmVndJ1EiKGvZWeLlgOFzH6hqdN3ucaIO1W8Juwm4HJ7B4scUijd7s5xqtpC3GjjvjTeCx/usr+no40M1roDScCxpgAbTlm18L+lTG3Iuvf8U+5wWE3rvkCfo2Tn3P6auFO/ayqBNojkmDBvKvdGxoxiJ6quhdgzFaDDsRQJmX0lrUlTXJJtW9FnkI9p6HJRUA7MZThWMxhhCjTsBZJ/Fo4ql2pHCYG4GmfbDLimzD3NwHOL1HKiysn4RV59lyM3K6zYpJJcY/+8c9JvzpiKlMxib6h8oAp9r5UgcdbtKuXbh08NNUlqCn47wYO+keH/fkgbsRvcGYTj0fvfsZapcgnDN++wg2iQxUkoP0AMkzqCitH7DHMDAiOjkCBQyUmxMnAn/8jIxd69NfZnJ1oq8xVoxRiLtPU49FyFw9dByDULOH+MYVmVCSyeVBRoThqMae1pZ/vpi75rBPuld/eryVOfw1NHAuqjnDKE4C9tdUbD5crUf9eWcMuS8+XNgUDxFYDIykPWaqCP0sM9c6S4s7F2GnQoG2qdYSBFO3oUBpoKFCFy1OvwRSgxN4pimMrVdTW+R+ZsQYFnqEeIf/UKp5AbHmX3yDz+JipTLxy+OllarD3JmuE6R/v3K+ReABseDlzRQQAJxdEYv892JVqHFUk=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: LiX3PFBjOuBODyMyFavy4mqRfb0NHq83PAYLllk3+hagBuP0m9R76yWoeDKKUVRQuPXnh23ryzouIN4irl1GjxI09ia9Sa7zo4kDN50UVG6Z5LDi/Wo0FEgTiBmpGgHfxbWCoIrWQEWFpnF5+1iKJftvgkIpVQGByCn8m+XT+yCIad8p3HVr4LahU3+djiU4T4Or1IpacHmzx7CrU2+K7bUH9ZkLs4kf3Cd+IRv6tJBfyBFgFmumTTkbcFjwILDhkVRMbiFwmDw8SVXmE3WM/VUGQxbxtL1DHg+NOd5Z2yl6CcDizWF9+rIqeQKyISnyu8/5yYRR2sNkWYLjUitYFCdVPEsmwocM9D3QJaIG26zdeIyRbriF3iLuQSGEODQrURASxChMirL6mwbdTNwouCGyR4+rpk5EGDwxT++gF64CgjGNkY6sQrt0c++qKnDkST7nV8dm9Zh1y+kvXFY1RnAqiGKxsjKL5BB3nWcRdWEFOvcu+KdSR9nsry0nXKiFFDjaclqa8LyGQ96islEC4UHizxdy1fbupYTbGH92sFBanPb9XlQSZy3Vzqv2fFSfvX5TjZLS9s0RKwTQS0sJYRehNTVE9BjYgkHJgu4uJzS8lh8emzcVmkZIOJbALc8Vi1ZEPQ6thphMjizTicQUCm8pxVoIgwJNPX6jku/4/Dc=
  on:
    branch: master
    repo: plepers/nanogl-node
